--- #YAML:1.0
name:                Devel-TraceVars
version:             0.01
abstract:            Print each line of code with variables evaluated
license:             ~
author:              
    - Emmanuel Rodriguez <potyl@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    PadWalker:                     0.10
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
